module Main where

import Data.List (isSuffixOf)
import System.Directory (doesDirectoryExist, doesFileExist)
import System.Directory.Extra (listDirectories)
import System.Environment (getArgs)

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help", "-h"] -> putStrLn "Usage: git keep [options]"
    ["--version", "-v"] -> putStrLn "git-keep version 1.0"
    _ -> do
      let isRecursive = any (`elem` ["--recursive", "-r"]) args
      createGitkeep isRecursive "."

-- Create .gitkeep file(s)
createGitkeep :: Bool -> FilePath -> IO ()
createGitkeep isRecursive path = do
  isDirectory <- doesDirectoryExist path
  ignoredFolders <- getIgnoredFolders path
  if not isDirectory || path `elem` ignoredFolders
    then return ()
    else do
      let gitkeepPath = path ++ "/.gitkeep"
      appendFile gitkeepPath "Generated by git-keep"

  if isRecursive
    then do
      dirs <- listDirectories path
      mapM_ (createGitkeep True) dirs
    else return ()

-- Get ignored folders from .gitignore file
getIgnoredFolders :: FilePath -> IO [String]
getIgnoredFolders path = do
  gitignoreExists <- doesFileExist (path ++ "/.gitignore")
  if gitignoreExists
    then do
      ignored <- readFile (path ++ "/.gitignore")
      return $ filter (\l -> isFolder l) (lines ignored)
    else return []

-- Check if a path is a folder
-- TODO: Implement for other folder patterns
isFolder :: String -> Bool
isFolder path = "/" `isSuffixOf` path
